use reagail;
INSERT INTO items (name, description, color, category, brand, quantity, price) VALUES
('The Classic', 'A timeless piece that never goes out of style', 'Black', 'Eyeglasses', 'Gucci', 10, 299.99),
('The Aviator', 'A classic style with a modern twist', 'Gold', 'Sunglasses', 'Ray-Ban', 15, 349.99),
('The Bookworm', 'A stylish pair of reading glasses that will make you look smart', 'Red', 'Reading glasses', 'Prada', 5, 99.99),
('The Diva', 'A fashion statement that will turn heads', 'Pink', 'Fashion glasses', 'Chanel', 20, 599.99),
('The Roundabout', 'A pair of round glasses that will make you look hipster', 'Brown', 'Eyeglasses', 'Tom Ford', 8, 399.99),
('The Wayfarer', 'A classic design that never goes out of style', 'Black', 'Sunglasses', 'Persol', 12, 299.99),
('The Professor', 'A pair of reading glasses that will make you look like a genius', 'Black', 'Reading glasses', 'Armani', 3, 149.99),
('The Trendsetter', 'A fashion-forward design that will make you the talk of the town', 'Purple', 'Fashion glasses', 'Dior', 25, 799.99),
('The Cat-Eye', 'A pair of glasses that will give you a retro look', 'Red', 'Eyeglasses', 'Marc Jacobs', 6, 299.99),
('The Pilot', 'A classic style that will make you look like a pilot', 'Silver', 'Sunglasses', 'Porsche Design', 20, 449.99),
('The Scholar', 'A pair of reading glasses that will make you look like you belong in a library', 'Brown', 'Reading glasses', 'Versace', 7, 129.99),
('The Bold', 'A pair of glasses that will make a statement', 'Black', 'Fashion glasses', 'Fendi', 15, 599.99),
('The Rectangle', 'A pair of glasses that will make your face look slimmer', 'Black', 'Eyeglasses', 'Gucci', 9, 399.99),
('The Clubmaster', 'A classic design that will never go out of style', 'Brown', 'Sunglasses', 'Tom Ford', 18, 349.99),
('The Intellectual', 'A pair of reading glasses that will make you look like a philosopher', 'Black', 'Reading glasses', 'Hugo Boss', 4, 99.99),
('The Iconic', 'A fashion-forward design that will make you stand out', 'Blue', 'Fashion glasses', 'Gucci', 30, 899.99),
('The Square', 'A pair of glasses that will give your face a strong look', 'Black', 'Eyeglasses', 'Prada', 11, 449.99),
('The Oversized', 'A pair of glasses that will make a statement', 'Brown', 'Sunglasses', 'Chanel', 22, 699.99),
('The Wise', 'A pair of reading glasses that will make you look wise', 'Brown', 'Reading glasses', 'Dior', 6, 149.99),
('The Glamorous', 'A pair of glasses that will make you look like a celebrity', 'Gold', 'Fashion glasses', 'Jimmy Choo', 35, 999.99),
('The Retro', 'A pair of glasses that will take you back to the 70s', 'Purple', 'Eyeglasses', 'Gucci', 7, 349.99),
('The Sporty', 'A pair of glasses that will keep up with your active lifestyle', 'Black', 'Sunglasses', 'Oakley', 16, 299.99),
('The Scholarly', 'A pair of reading glasses that will make you look like a scholar', 'Black', 'Reading glasses', 'Prada', 5, 119.99),
('The Edgy', 'A pair of glasses that will give you an edgy look', 'Silver', 'Fashion glasses', 'Alexander McQueen', 28, 799.99),
('The Cat-Eye II', 'A pair of glasses that will give you a retro look', 'White', 'Eyeglasses', 'Dolce & Gabbana', 9, 399.99),
('The Polarized', 'A pair of sunglasses that will protect your eyes from UV rays', 'Brown', 'Sunglasses', 'Gucci', 14, 449.99),
('The Intellectual II', 'A pair of reading glasses that will make you look like a philosopher', 'Brown', 'Reading glasses', 'Giorgio Armani', 4, 99.99),
('The Chic', 'A pair of glasses that will make you look fashionable', 'Black', 'Fashion glasses', 'Prada', 30, 899.99),
('The Geometric', 'A pair of glasses with a unique geometric design', 'Gold', 'Eyeglasses', 'Fendi', 12, 449.99),
('The Roundabout II', 'A pair of glasses that will make you look hipster', 'Black', 'Sunglasses', 'Dior', 19, 399.99);
